### ISSUE TITLE
Incorrect time displayed for bad response time widget

### ISSUE THREAD

**Issue by hanikhan** [MarcosEllys/awesome-newman-html-template#12]
**Describe the bug**
Run a few requests with this template and observe the bad response time

**To Reproduce**
1. Run any collection using this hbs
2. Incorrect time displayed under 'Bad Response Time' 

**Expected behavior**
Should display correct time

**Comment by MarcosEllys** [comment]
Hi @hanikhan thank you so much for fix this issue, feel free to post new improvements and fixes

**Comment by hanikhan** [comment]
Sure!

Thanks for merging the changes. You may close this issue
