### ISSUE TITLE
Best response time is coming 0 ms in the Report

### ISSUE THREAD

**Issue by BhanuDash007** [MarcosEllys/awesome-newman-html-template#18]
Best response time is coming 0 ms in the Report.
Requests Without Tests missing the icon ( ).

**Comment by MarcosEllys** [comment]
Oh, it's my fault, thanks @BhanuDash007 for report this, i will fix coming soon

**Comment by MarcosEllys** [comment]
Hey @BhanuDash007, i can't reproduce this behavior, can you send a collection with one example or show a image?
