### ISSUE TITLE
Could you please add Graph / Pie chart to the reports.

### ISSUE THREAD

**Issue by BhanuDash007** [MarcosEllys/awesome-newman-html-template#19]
If Some thing can be done the we have the Extent report it will be very nice,

I have attached a Sample extent report for reference.

![sample_extent report](https://user-images.githubusercontent.com/25523060/45859047-f8c68700-bd25-11e8-9da7-4396bb98ec65.png)

**Comment by MarcosEllys** [comment]
Sure, it's a beautiful sample, in this moment i don't have a suitable model for the template, but, it would interesting aggregate some information's in a graph, do you have some idea which are data could aggregate?

Thanks for advice.

**Comment by BhanuDash007** [comment]
It will good if we can put the Pass , Fail and No run % it will be good. As well as if you can system info in report will be nice.

**Comment by BhanuDash007** [comment]
Can you add start time , end time also ? The header should be green for pass , light red for fail , yellow for no run . Body would be 1 color ex .purple will be nice and all result box should be connected with no space so that it will be feel like a Dashboard.

**Comment by MarcosEllys** [comment]
> Can you add start time , end time also ? The header should be green for pass , light red for fail , yellow for no run . Body would be 1 color ex .purple will be nice and all result box should be connected with no space so that it will be feel like a Dashboard.

Postman API don't return any data about start/end time (except one string), but it's interesting, maybe we can to add

**Comment by MarcosEllys** [comment]
And about graphics that I will not add for now, because, I want to improve the mobile experience, in the report tab is ok

![image](https://user-images.githubusercontent.com/6751242/45960228-23e4fb00-bff2-11e8-91b5-331a29842f73.png)

But i neeed to improve in the requests tab
