### ISSUE TITLE
Query on awesome-newman-html-template

### ISSUE THREAD

**Issue by BhanuDash007** [MarcosEllys/awesome-newman-html-template#20]
hi Marcos,

Your Postman Report is very good. If you want we can work together and build a great report that can be used   larger community. If you want i can write few more features for you. 

Please let me know if you want it and we can go from their.

Thanks
Bhanu

**Comment by MarcosEllys** [comment]
Hi @BhanuDash007, thanks, it's wonderful to hear this and I'm grateful that you enjoyed it.

Yeah, it would great work with you and add more features just only send as pull request and we go analyze together.

Best regards
