### ISSUE TITLE
Change widget color

### ISSUE THREAD

**Issue by MarcosEllys** [MarcosEllys/awesome-newman-html-template#23]
## Description

Change the current widget Requests in the Report tab to purple colors

## Current widget

![image](https://user-images.githubusercontent.com/6751242/46563229-b3ce5300-c8d6-11e8-88c7-c2db64b0e684.png)

## File

[htmlreqres.hbs](https://github.com/MarcosEllys/awesome-newman-html-template/blob/master/templates/htmlreqres.hbs)

**Comment by Janice0218** [comment]
can i take it?

**Comment by MarcosEllys** [comment]
Sure :)

**Comment by MarcosEllys** [comment]
I'm sorry @Janice0218 but you need to create and change two new class

- widget-heading-purple
- widget-body-purple

and in the css style modify theses classes for appropriate colors :laughing:

**Comment by MonilBhavsar** [comment]
I can do it :)

**Comment by MarcosEllys** [comment]
Thank you for everyone, the pull request of @MonilBhavsar, was acceptable.
