### ISSUE TITLE
Add Postman favicon

### ISSUE THREAD

**Issue by MarcosEllys** [MarcosEllys/awesome-newman-html-template#24]
## Description

I need to add a postman favicon (preferably base64) in the template

## File

[htmlreqres.hbs](https://github.com/MarcosEllys/awesome-newman-html-template/blob/master/templates/htmlreqres.hbs)

**Comment by stephdavl** [comment]
Can I work on this?

**Comment by MarcosEllys** [comment]
Sure :smile:

**Comment by stephdavl** [comment]
I just did a pull request with the favicon!  #30
