### ISSUE TITLE
Add Highlight.Js in the Readme

### ISSUE THREAD

**Issue by MarcosEllys** [MarcosEllys/awesome-newman-html-template#27]
## Description

Add [highlight.js](https://highlightjs.org/) in the **Libraries present** section

## File

[Readme](https://github.com/MarcosEllys/awesome-newman-html-template/blob/master/README.md)

**Comment by ztmeyer** [comment]
I can help you with this @MarcosEllys, could you assign the issue to me?

**Comment by MarcosEllys** [comment]
Sure :smile:

**Comment by MarcosEllys** [comment]
I can't but you can make this, I'll wait for you

**Comment by amrs-tech** [comment]
If he's not doing, I'll do it @MarcosEllys

**Comment by ztmeyer** [comment]
Hey @MarcosEllys - I just created #28 for this issue, let me know what feedback you have
