### ISSUE TITLE
Webservice polling (repeat execution) shows first response in report instead of the last

### ISSUE THREAD

**Issue by trantoriana** [MarcosEllys/awesome-newman-html-template#35]
Hi,

I noticed that when implementing some (repeated) web service polling the step response is showing the response of the first step invocation instead of the expected last one.
The polling webservice 'interpretes' the output and repeats itself until a 'asynchronous webservice' status is finished.

Consider this test:

1) Call some asynchronous webservice A
2) Poll web service B, which does something like
    a) Wait for 5 secs
    b) Call status asynchronous webservice A
    c) If status Web service A is not 'finished' => goto a) through "postman.setNextRequest(pm.info.requestId);"
    d) Run the tests for step 2

(I do not have a good generic example for above other than mine which does not work in the wild.)

The issue with the report is that the response of web service B is the response of the very first invocation of the polling web service, however the last invocation is of course the one which we are interested in.

Not knowing node or how to actual show the complete test collection output, I assume ALL tests responses are available and the report generation should just be updated to show that last response of the polling service.

Any idea how to start addressing this ?

Thanks, Tran.

**Comment by MarcosEllys** [comment]
Hi @trantoriana, unfortunately this is the natural behavior of newman and not a template problem, so far, there is nothing to do.
