### ISSUE TITLE
All Calls not visible under Requests -> Show All tab for Newman Iteration Requests

### ISSUE THREAD

**Issue by guptarajatkn** [MarcosEllys/awesome-newman-html-template#36]
**Describe the bug**
Under The Requests -> Show All tab, only Two Request are visible for Iteration Calls _( I did 3000 Iterations for collection of 2 calls)_

Similarly Many Details are missing for the ouput.

**To Reproduce**
Do a Newman Execution with Iterations for a collection having multiple API calls

**Expected behavior**
As for normal newman execution, Details for all the calls be it in Iteration should be visible clearly.

**Screenshots**
![image](https://user-images.githubusercontent.com/17121923/49286607-b1483e00-f4c0-11e8-89c9-342290bb17a1.png)

**Comment by MarcosEllys** [comment]
Hello @guptarajatkn it's a huge problem, but when i investigate this, i discovered that is the default behavior of the newman and not an error in my template, therefore unfortunately i can't fix it.
