### ISSUE TITLE
Showing where the failures occured

### ISSUE THREAD

**Issue by LHemingway** [MarcosEllys/awesome-newman-html-template#7]
Thank you for the template it is very well designed. 

I'm currently having a problem that it doesn't tell me where the error occurred. If I'm running multiple iterations with a large data-set and there have been 5 failures it will tell me this but not where the failures occurred like it does in the standard newman HTML reporter. 

![image](https://user-images.githubusercontent.com/31653164/45166372-c3cb1800-b1ee-11e8-8c4b-0ee03ff532ef.png)

**Comment by MarcosEllys** [comment]
Thank's for the info, well, i see now that have some new params in the default template, then, i wiil check that's possibile implement (it should be possible, i think).

My schedule to deploy this will be a week at the most.

**Comment by MarcosEllys** [comment]
Feature implemented.

![image](https://user-images.githubusercontent.com/6751242/45214884-0a158b00-b272-11e8-9938-8265fe2ad79d.png)

**Comment by LHemingway** [comment]
That's great! Thank you very much for the quick turn around. 

![image](https://user-images.githubusercontent.com/31653164/45221631-f423bc80-b2a9-11e8-8e29-480e44f20b27.png)
